---

    group: stable
    dist: xenial
    sudo: required
    
    language: python
    python:
      - 3.7
    cache: pip
    
    branches:
      only:
        - develop
        - master
    
    env:
      jobs:
        - ANSIBLE_INSTALL_VERSION: 2.7.18
        - ANSIBLE_INSTALL_VERSION: 2.8.14
        - ANSIBLE_INSTALL_VERSION: 2.9.12
    
    before_install:
      # Upgrade Docker to work with docker-py.
      - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash
    
    install:
      # Install test dependencies.
      - pip install molecule yamllint ansible-lint docker
    
    script:
        - molecule test -s default

    services:
      - docker