---

group: stable
os: linux
dist: xenial

language: python
python:
  - 3.7
cache: pip
    
branches:
  only:
    - develop
    - master

env:
- MOLECULE_DISTRO=centos:7
  ANSIBLE_INSTALL_VERSION=2.8.13
- MOLECULE_DISTRO=centos:7
  ANSIBLE_INSTALL_VERSION=2.9.12
- MOLECULE_DISTRO=centos:8
  ANSIBLE_INSTALL_VERSION=2.8.13
- MOLECULE_DISTRO=centos:8
  ANSIBLE_INSTALL_VERSION=2.9.12
- MOLECULE_DISTRO=jrei/systemd-debian:8
  ANSIBLE_INSTALL_VERSION=2.8.13
#   CMD="apt-get install -y init&&/usr/sbin/init"
# - MOLECULE_DISTRO=debian:jessie
#   ANSIBLE_INSTALL_VERSION=2.9.12
# - MOLECULE_DISTRO=debian:buster
#   ANSIBLE_INSTALL_VERSION=2.8.13
# - MOLECULE_DISTRO=debian:buster
#   ANSIBLE_INSTALL_VERSION=2.9.12
# - MOLECULE_DISTRO=ubuntu:focal
#   ANSIBLE_INSTALL_VERSION=2.8.13
#   CMD="/sbin/init"
# - MOLECULE_DISTRO=ubuntu:focal
#   ANSIBLE_INSTALL_VERSION=2.9.12
#   CMD="/sbin/init"
# - MOLECULE_DISTRO=ubuntu:bionic
#   ANSIBLE_INSTALL_VERSION=2.8.13
#   CMD="/sbin/init"
# - MOLECULE_DISTRO=ubuntu:bionic
#   ANSIBLE_INSTALL_VERSION=2.9.12
#   CMD="/sbin/init"
  
addons:
  apt:
    packages:
      - docker-ce
install:
  - pip install ansible==${ANSIBLE_INSTALL_VERSION} molecule==3.0.6 yamllint ansible-lint==4.2.0 docker==4.2.2 testinfra==5.2.2

script:
    - molecule test -s default
    - ansible --version

services:
  - docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
