---

    group: stable
    dist: xenial
    sudo: required
    
    language: python
    python:
      - 3.7
    cache: pip
    
    branches:
      only:
        - develop
        - master
    
    env:
      - ANSIBLE_INSTALL_VERSION=2.8.13
      - ANSIBLE_INSTALL_VERSION=2.9.12
    

    script:
        - pipenv run molecule test --all

    services:
      - docker