---

    group: stable
    dist: xenial

    language: python
    python:
      - 3.7
    cache: pip
    
    branches:
      only:
        - develop
        - master
    
    env:
      ANSIBLE_INSTALL_VERSION: 
        - "2.7.18"
        - "2.8.14"
        - "2.9.12"
      jobs:
        - MOLECULE_DISTRO: centos:7
        - MOLECULE_DISTRO: centos:8
        # - MOLECULE_DISTRO: centos:9
        # - MOLECULE_DISTRO: fedora:28
        # - MOLECULE_DISTRO: ubuntu:xenial
        - MOLECULE_DISTRO: debian:jessie

    script:
        - molecule test -s default

    services:
      - docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
