---

    group: stable
    dist: xenial
    sudo: required
    
    language: python
    python:
      - 3.7
    cache: pip
    
    branches:
      only:
        - develop
        - master
    
    env:
      - ANSIBLE_INSTALL_VERSION=2.8.13
      - ANSIBLE_INSTALL_VERSION=2.9.12
    
    services:
      - docker
    
    before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce