---

group: stable
dist: xenial

language: python
python:
  - 3.7
cache: pip
    
branches:
  only:
    - develop
    - master

env:
- MOLECULE_DISTRO=centos:7
  - ANSIBLE_VERSION=2.7.18
  - ANSIBLE_VERSION=2.9.12
  - ANSIBLE_VERSION=2.8.13
- MOLECULE_DISTRO=centos:8
- MOLECULE_DISTRO=fedora:28
    # - MOLECULE_DISTRO: ubuntu1804
    # - MOLECULE_DISTRO: fedora:28
    # - MOLECULE_DISTRO: jrei/systemd-ubuntu:20.04
    # - MOLECULE_DISTRO: jrei/systemd-debian:8
    # - MOLECULE_DISTRO: debian:jessie
    # - MOLECULE_DISTRO: debian:buster

addons:
  apt:
    packages:
      - docker-ce

script:
    - molecule test -s default

services:
  - docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
