---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-centos:8}"
    # pre_build_image: true
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "{CMD:-/usr/sbin/init}"
    environment: { container: docker }

provisioner:
  name: ansible
  log: True
verifier:
  name: testinfra
scenario:
  name: default
