---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-centos:8}"
    # pre_build_image: true
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment: { container: docker }

provisioner:
  name: ansible
  log: True
verifier:
  name: testinfra
scenario:
  name: default
  test_sequence:
    ─ dependency
    ─ lint
    ─ cleanup
    ─ destroy
    ─ syntax
    ─ create
    ─ prepare
    ─ converge
    ─ idempotence
    ─ side_effect
    ─ verify
    ─ cleanup
    ─ destroy
