---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-centos8
    image: ${MOLECULE_DISTRO:-centos:8}
    pre_build_image: true
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment: { container: docker }

provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - lint
    - verify
